services:
  web:
    build: . 
    ports:
      - 80:3000
    environment:
      - NODE_ENV=production
    volumes:
      - /app/node_modules
  postgres:
    image: postgres:11-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password

volumes:
  postgres-data:
